name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [synchronize]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1', '3.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ matrix.ruby }}
      #     bundler-cache: true

      - name: Get modified files
        run: |
          echo "Modified files in the PR:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Run CI steps
        run: echo "Running CI jobs..."

  commitlint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
