name: Block Invalid PR

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check PR Content
        id: intercept
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/workflows/scripts/pr-filter.js');
            const result = await script({ github, context });
            core.setOutput('result', result);

      - name: Abort due to invalid PR
        if: ${{ steps.intercept.outputs.result == 'false' }}
        run: exit 1

  test:
    needs: check-template
    uses: ./.github/workflows/ci.yml
