name: Block Invalid PRs

on:
  pull_request_target:
    types: [opened, reopened, edited]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR body against template
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/workflows/scripts/pr-filter.js');
            await script({ github, context });
